### ISSUE TITLE
[Feature] Ability to add custom chains

### ISSUE THREAD

**Issue by belg1o** [RabbyHub/Rabby#1274]
What?

The ability to add custom chains is one feature that Rabby really lacks. 

Why? 

A lot of chains are being deployed and being able to add them ourselves before a Rabby implementation is crutial for developers and early adopters of chains. I do not want to have to switch back and forth between wallets constantly to be able to explore and use a chain that is not yet added.

Nice to have:

The ability to import chains via https://chainlist.org/

**Comment by fastackl** [comment]
Yup - product is awesome. I want to use it for testing contracts. That would require Rabby to allow me to add Goerli test network. Can't see to find a way to do that

**Comment by edmundedgar** [comment]
Just to add to this - I just tested Rabby after installing it a year or so ago and absolutely loved it, and was about to add it to my dapp's "recommended" screen that we show when you show up without a web3-enabled browser. (We originally recommended MetaMask but we removed that when they changed to a non-free license.) But then I went to test it with Goerli and that was missing and I couldn't add it, and some of the other chains we support were also missing.

This is a blocker for me and the only one - I'll definitely recommend this wallet once it's fixed.

**Comment by rummzink** [comment]
I look forward to remove Metamask from my browser and use Rabby as replacement. But it seems like lacking of the ability to add custom networks (i mean any network of user's choice) is preventing users from getting rid of Metamask.

**Comment by belg1o** [comment]
@vvvvvv1vvvvvv 

Could you please focus on this soon? I've noticed you've been adding chain support over time, which is great but please allow us to add our own networks & chains with allowing us to define the RPCs. 

This would solve all the following open requests:
#1379 #1360 #1369 #1212 #1066 #1049 #976 #974 #867 #826 #612 #353

**Comment by belg1o** [comment]
> @vvvvvv1vvvvvv
> 
> Could you please focus on this soon? I've noticed you've been adding chain support over time, which is great but please allow us to add our own networks & chains with allowing us to define the RPCs.
> 
> This would solve all the following open requests: #1379 #1360 #1369 #1212 #1066 #1049 #976 #974 #867 #826 #612 #353

cc: @heisenberg-2077 @dmy147 @cs1707

**Comment by xHmmmmm** [comment]
This functionality is so crucial for a complete wallet experience and yet Rabby's developers seem to overlook that particular topic strictly. While the concerns about quality of experience when using Rabby sound fair enough, the testnets aren't there for pleasure of use but to test things out and improve the network, and the idea of waiting for the developers to manually integrate a new chain every time one rolls out is just ridiculous and won't make the cut given number of new blockchains being created all the time.

Please add support for custom chains (maybe allow users to toggle this as an option in the settings). This is literally the only reason I stick to Metamask with its clunkiness and questionable ToS, instead of better in every other way Rabby. I suspect it's a deal-breaker for many potential users.

**Comment by Dereek69** [comment]
Agree with the other posts in this thread.
Having the ability to add custom chains is essential for a complete experience on a wallet. After seeing rabby being shared i download and had a really good time using it, until after the realization that it didnt support custom chains i was forced to freeze the extention and install metamask once again.
Its simply not possible for the developers of the projects to be up to date with every new chain and testnet deployed but users will need to interact with them.

Please make this a priority because its really badly needed

**Comment by radeksvarz** [comment]
+1 for prio
This is critical to use Rabby during trainings and demonstrations. We are stuck with MM for now :(

**Comment by latifrons** [comment]
+1 
For normal users it is also important to switch between RPCs for the same chain id.
e.g. when playing with DeFi, users may switch to Flashbot protected RPC to prevent front-running, while for other txs they may switch to normal rpc (or infura rpc, alchemy rpc, etc) for fast confirmation.

and for devs both chain id and rpc need customization.

**Comment by stevyhacker** [comment]
+1 on this issue, it's very useful to have testnet support for devs and custom chain support for advanced users.

**Comment by dapp-whisperer** [comment]
+1, to testnet and custom RPC, this is the only reason I have MM still installed

**Comment by StayFoolisj** [comment]
+1 on having the ability to add testnets, quite surprised they've not prioritised this

**Comment by wsdt** [comment]
++++

**Comment by hdadr** [comment]
++++

**Comment by pripatelUK** [comment]
+++

**Comment by lucasregueiroo** [comment]
+1

**Comment by aquaticone** [comment]
+1

**Comment by danyeah** [comment]
Any update on this?
Not having custom chains and testnets is a real pain. 
Do you guys not use testnets at all???

**Comment by mdrlucky** [comment]
+1 without this feature, to be able to add testnets, users has to keep MM.
it majors risks for the users, and for you, you will lose market share once MM will issue news functionalities, add ins etc ..

**Comment by lucasregueiroo** [comment]
at least we got some testnets now lol

**Comment by dedosmedia** [comment]
Sepolia Tesnet please!

**Comment by vacekj** [comment]
@vvvvvv1vvvvvv Is there anything that I could do to expedite this feature? I'm more than happy to help move this forward.

**Comment by aspiers** [comment]
Oh wow, I was enjoying Rabby so much in these first few days and then I discovered this which is a total deal-breaker for me (I need Celo's Alfajores testnet).  What a shame to stumble at the last hurdle after doing so amazingly well in all other respects!  Given the overwhelming demand for this feature, it's a bit worrying that there hasn't been any comment on this issue from any Rabby devs.  Are they aware of this?  I guess I'll try to raise it on Discord.

**Comment by jurosh** [comment]
Seems like a deal-breaker to me too. As developers, we aren't only using public chains, and so without ability to add custom Chain (RPC, ChainId, Explorer) it's hard to test dApp with Rabby wallet.

Having ability to add custom chain might be needed also for L2 Chains of [Polygon Supernets](https://polygon.technology/polygon-supernets).

**Comment by trendespresso** [comment]
Any update on this?
Why can't we add custom chains???
At the very minimum, please add a "Localhost:8545" option where the ChainID is 31337.

**Comment by rkjdid** [comment]
bumping this yes

**Comment by davidtacer** [comment]
+1

**Comment by berabuilder** [comment]
+1

**Comment by radeksvarz** [comment]
> Any update on this? Why can't we add custom chains??? At the very minimum, please add a "Localhost:8545" option where the ChainID is 31337.

I somehow understand the need for caution.

Thats why I propose a separate approach for dev localhost: #1417

**Comment by aspiers** [comment]
Apparently no response from the team here, so I sent [this message on their Discord](https://discord.com/channels/859693143934763067/907888985332912188/1193922990858051604).  It's clear that adding +1 comments here does nothing useful, so if you want this feature, please consider chiming in on Discord or trying to reach the Rabby team via other communication channels.

**Comment by kamikazebr** [comment]
> Apparently no response from the team here, so I sent [this message on their Discord](https://discord.com/channels/859693143934763067/907888985332912188/1193922990858051604). It's clear that adding +1 comments here does nothing useful, so if you want this feature, please consider chiming in on Discord or trying to reach the Rabby team via other communication channels.

Can we fork the project to add those?

**Comment by 0xKurt** [comment]
bump for interest

**Comment by eyooooo** [comment]
please fckin add this or just keep up to date with it. op goerli shut down WEEKS ago and rabby still hasnt added op sepolia.

**Comment by vvvvvv1vvvvvv** [comment]
You can add custom testnet in Rabby now, so the issue will be closed

**Comment by aspiers** [comment]
Seems like there is a misunderstanding or miscommunication here.  The feature appears to be for custom _**testnets**_ only, but the requested feature was for _**any**_ custom chain (even mainnets).

![image](https://github.com/RabbyHub/Rabby/assets/100738/b5b4e6eb-de41-4a68-aace-0782f37c779b)

**Comment by vvvvvv1vvvvvv** [comment]
There is no limitation, you can also add any mainnet by this function but what we want to let you know is we will consider all custom network as testnet so there will no security features for these network

**Comment by aspiers** [comment]
Thanks that's good to know, but it's still confusing for the UI to present the option as "Custom Testnet" because this makes it look like custom mainnets cannot be added.  The presence of the "Enable Testnets" toggle just above it makes it look like any custom network added via "Custom Testnet" will not be available if that toggle is disabled, which is counterproductive if the custom network added is actually a mainnet.  So I suggest renaming the "Custom Testnet" option to "Custom network" or "Custom chain", or rethinking the design in some other way.
