### ISSUE TITLE
Security issue: cryptography is bad, outdated, prone to supply chain risks

### ISSUE THREAD

**Issue by paulmillr** [RabbyHub/Rabby#1334]
In your [package.json](https://github.com/RabbyHub/Rabby/blob/develop/package.json) you use stuff like:

- crypto-browserify
- @ethereumjs/util (old version) AND ethereumjs-util (even older version)
- ethers 5 (old version)
- hdkey, bip32 (old versions)
- probably other dependencies and their subdependencies

They use insecure, old cryptography. 

In 2022, audited cryptography stack for Ethereum has been released https://github.com/ethereum/ethereum-cryptography [(blog post)](https://paulmillr.com/posts/eth-cryptography/), which uses modern minimalistic libraries. The libraries depend on https://github.com/paulmillr/noble-hashes and https://github.com/paulmillr/noble-curves. 

It is strongly recommended to upgrade your cryptography, keeping old stuff around is dangerous:

- Bad cryptography can leak user's private key even when it's not used for key generation
- A dependency could have a "malwared" upgrade which rabby will consume because there are no real dep audits

**Comment by paulmillr** [comment]
That's good that you don't use them for keygen.

Upgrade is still a security requirement because of supply chain risks. Noble is tiny. These libraries are like 30k lines of unnecessary code that you likely won't re-audit on every dep update.

The code can do nasty stuff and contain malware.

**Comment by ajb** [comment]
thanks @paulmillr for your excellent work as always

i will also say, i'm not even sure this matters until rabby open-sources their closed-source dependencies: #1019 

anyone with an ounce of security training is going to keep using metamask for now.

**Comment by feld** [comment]
> thanks @paulmillr for your excellent work as always
> 
> i will also say, i'm not even sure this matters until rabby open-sources their closed-source dependencies: #1019
> 
> anyone with an ounce of security knowledge is going to keep using metamask for now.

This was resolved: https://github.com/RabbyHub/Rabby/issues/1019#issuecomment-1598042074

**Comment by paulmillr** [comment]
@vvvvvv1vvvvvv actually I just investigated rabby in deep and realized it is using terrible, old packages for actual private key management (https://www.npmjs.com/package/@rabby-wallet/eth-simple-keyring etc).

And there have been no action for almost half a year in the issue.

At this point I can confidently call rabby security a shit.

**Comment by engn33r** [comment]
I was about to open an issue for this but found that @paulmillr has summarized the situation well. The resolution of this issue needs to be prioritized.

To describe it in a slightly different way, the [OWASP top 10](https://owasp.org/www-project-top-ten/) summarizes the most common security issues observed in practice. There are many instances of "Vulnerable and Outdated Components" here, which means the code used by Rabby (from importing these dependencies) is much less secure than it could be. And I'm only looking at the direct dependencies, not the dependency tree used by the outdated and excessively large dependencies. The situation has been this way, unchanged, for months.

The dependencies used here need a serious overhaul and should be regularly updated, which is not happening. Running `yarn audit` on the latest release returns 21 high severity issues with the current dependencies that can be fixed by updating the dependency version.

I am surprised that the public Rabby pen test reports make no mention of any dependency-related issues. This is a very standard item to check for in such tests and easy to identify. I suggest a different security firm for the next pen test.

**Comment by PhuocHofu** [comment]
@paulmillr @engn33r So seeds created from rabby wallets have always been a security risk?
Thanks!

**Comment by paulmillr** [comment]
@PhuocHofu the risk is not enormous, but there is some. I'm not sure how good the randomness of rabby is

**Comment by vvvvvv1vvvvvv** [comment]
@paulmillr for randomness, Rabby using bip39 for generate mnemonic https://github.com/RabbyHub/eth-hd-keyring/blob/main/index.ts#L97
there is no way to generate private key in Rabby so no randomness requirement for private key

**Comment by vvvvvv1vvvvvv** [comment]
the randomness for bip39 you can check here https://github.com/bitcoinjs/bip39/blob/master/src/index.js#L135

**Comment by vvvvvv1vvvvvv** [comment]
and Rabby is working on a LavaMoat webpack plugin so that we can have the same supply chain protection as MetaMask

**Comment by paulmillr** [comment]
> there is no way to generate private key in Rabby so no randomness requirement for private key

There is no difference in "bip39 randomness" versus "private key randomness" for users. If either is compromised and weak, it's done

**Comment by vvvvvv1vvvvvv** [comment]
Sorry for fogot to update the progress:
1. Already migrate to @scure/bip39 and ethereum-cryptography 2 months ago, check: https://github.com/RabbyHub/eth-simple-keyring/pull/1 https://github.com/RabbyHub/eth-hd-keyring/pull/5 https://github.com/RabbyHub/Rabby/pull/1796
2. Why still some outdated dependencies? Since there are still some sub-dependencies and utils required, like bufferToHex, but no worry, Rabby no longer uses cryptographic algorithms of those outdated dependencies

So I'm going to close this issue @paulmillr

**Comment by vvvvvv1vvvvvv** [comment]
And for LavaMoat intergration, I opened another issue to track it https://github.com/RabbyHub/Rabby/issues/1891

**Comment by paulmillr** [comment]
This is just a beginning. You have other security issues to fix.

https://github.com/RabbyHub/Rabby/issues/1921
