### ISSUE TITLE
Issues signing with BitBox

### ISSUE THREAD

**Issue by stas** [RabbyHub/Rabby#1403]
To reproduce, please try to withdraw a positions on Camelot on Arbitrum.

![Captura de ecrã de 2023-05-22 21 15 35](https://github.com/RabbyHub/Rabby/assets/112147/795fd874-cccb-499d-a8bd-3fb49d6c7bf0)

**Comment by vvvvvv1vvvvvv** [comment]
@benma Can you help to check this?

**Comment by neoKushan** [comment]
Not sure if it's related, but I am also having trouble even connecting my BitBox02 wallet with Rabby. I've installed the bridge but Rabby doesn't want to connect, it just displays "Please check the connection with your wallet".  Occasionally the pairing code appears briefly but disappears.

Other wallets that connect work fine, it seems specific to Rabby.

Using Chrome on Windows 11.

**Comment by benma** [comment]
> Not sure if it's related, but I am also having trouble even connecting my BitBox02 wallet with Rabby. I've installed the bridge but Rabby doesn't want to connect, it just displays "Please check the connection with your wallet". Occasionally the pairing code appears briefly but disappears.
> 
> Other wallets that connect work fine, it seems specific to Rabby.
> 
> Using Chrome on Windows 11.

Do you have the BitBoxApp or other wallets open? Close all of them before using Rabby.

**Comment by benma** [comment]
> @benma Can you help to check this?

Would be helpful to see te `data` json that is being sent to the bb02 to be signed.

Generally it looks like a value is typed as uint but is passed `0x00`, which is not an int but a string. The BitBox02 lib accepts strings only if they are ints, i.e. without the `0x` prefix. 

Does the same thing work with the Rabby hot wallet?

**Comment by neoKushan** [comment]
> > Not sure if it's related, but I am also having trouble even connecting my BitBox02 wallet with Rabby. I've installed the bridge but Rabby doesn't want to connect, it just displays "Please check the connection with your wallet". Occasionally the pairing code appears briefly but disappears.
> > Other wallets that connect work fine, it seems specific to Rabby.
> > Using Chrome on Windows 11.
> 
> Do you have the BitBoxApp or other wallets open? Close all of them before using Rabby.
> 
> Also maybe a long shot: do you have citrix installed? If so, update it (we have seen some USB issues with users having citrix installed).

Hi,

The behaviour is different depending on if I have the Bitbox app open or not. I will try to list the possibilities:

With no other apps open and the bitbox02 disconnected, I get an expected error of no Bitbox02 connected:

If I then plug in the BitBox02 and retry, I see the pairing key briefly appear on the Bitbox02 and then "transaction rejected":

![image](https://github.com/RabbyHub/Rabby/assets/1029699/cc1bfa5a-ada1-4017-9d3a-373e3d9b97ee)

Note: I have not unlocked the bitbox02 at this point.

If I open the Bitbox application, this prompts to unlock my Bitbox02 - so I can do that by entering the password. With the Bitbox app still open, when I retry the Rabby signing I get "Unexpected NACK response":

![image](https://github.com/RabbyHub/Rabby/assets/1029699/a33bdd63-01b1-495f-adef-15436a125f98)

If I then close the Bitbox app without removing the Bitbox02 device, I then get the same "unexpected NACK response".

I do not have citrix installed. I am happy to try anything to debug this issue as it's very important to me. I tried building Rabby to debug the issue myself but it seems this is currently impossible due to #1317.

**Comment by benma** [comment]
@neoKushan are you running a VPN?

Does the BitBoxApp work fine?

Does Chrome work with myetherwallet.com to access the BitBox02?

Note again that the BitBoxApp should be closed when using Rabby or myetherwallet.

Try also without cable and without adapter if possible.

**Comment by neoKushan** [comment]
hey @benma what's your thoughts on this? Is this a completely different issue to what @stas is seeing or is it related? I'm happy to create a separate issue if that's easier. Unfortunately this issue puts me dead in the water for what I need from my BitBox02.

**Comment by benma** [comment]
@neoKushan yeah 100% a different issue.

**Comment by benma** [comment]
@stas @vvvvvv1vvvvvv for the original issue: any way to see the raw data json that should be signed?

https://github.com/RabbyHub/Rabby/issues/1403#issuecomment-1562615784

**Comment by neoKushan** [comment]
> @neoKushan yeah 100% a different issue.

Okay, I've opened issue #1422 and put as much relevant info in there as I can. I would appreciate any help and guidance on this, as without Rabby support, my Bitbox02 is effectively useless to me and I had high hopes for this device.

**Comment by vvvvvv1vvvvvv** [comment]
> @stas @vvvvvv1vvvvvv for the original issue: any way to see the raw data json that should be signed?
> 
> [#1403 (comment)](https://github.com/RabbyHub/Rabby/issues/1403#issuecomment-1562615784)

@benma Yes, simply click "View Raw"
<img width="508" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/77df4500-51c2-4b4a-8a76-8f7aa78a1af9">

**Comment by benma** [comment]
@stas can you do that and post the raw message? (if there is private info in it you could replace it with something else of the same format)

**Comment by stas** [comment]
Thank you @benma
