### ISSUE TITLE
Rabby API License / Open Source

### ISSUE THREAD

**Issue by wsdt** [RabbyHub/Rabby#1476]
RabbyApi is `UNLICENSED` and there seems to be no Github repository for looking at the actual code. 

https://www.npmjs.com/package/@rabby-wallet/rabby-api

Does Rabby have plans to actually OpenSource the API package and distribute it under the same license as RabbyWallet?

Otherwise despite the wallet being under MIT, there would be no way of using it as such since that single package is not licensed accordingly (+ the associated API). 

Thank you in advance!

@thisconnect @tallship 

---

When looking into the `dist` of the package, it seems that Rabby intentionally hides the code as the package is a simple Wrapper for the closed-source RabbyAPI: 

```ts
export const INITIAL_OPENAPI_URL = 'https://api.rabby.io';
export { CHAINS };
export const SIGN_HDS = [
    'x-api-ts',
    'x-api-nonce',
    'x-api-ver',
    'x-api-sign',
];
```

---

If you don't want to open-source the API - is there any chance for a paid plan or something like that if used commercially? 

Btw we are also happy to push upstream if we are able to use Rabby for our client project.

**Comment by tallship** [comment]
> RabbyApi is UNLICENSED and there seems to be no Github repository for looking at the actual code.

> https://www.npmjs.com/package/@rabby-wallet/rabby-api

> Does Rabby have plans to actually OpenSource the API package and distribute it under the same license as RabbyWallet?

## This is somewhat disturbing. 

I think *it is especially important that non-custodial wallets are FOSS based, and that all software directly related to its operation be FOSS* (and therefore accessible).

Indeed, permissive licenses are often seen as licenses which proprietary interests will simply rebrand, post the copyright, and repackage without making their code available - AGPL fixes this and installs confidence by the users since everything is vetted and all changes to the original code is required to be made available by hosting providers (i.e., SaaS); *GPL ensures the same ability for users that packaged products are distributed to.*

**If we can't see what's going on in the API then it's probably a good idea to simply not use that software anymore**, until such time as the omission is corrected.

⛵

.

**Comment by vvvvvv1vvvvvv** [comment]
@rabby-wallet/rabby-api is a package for call api of rabby-wallet, the package is not opensource for anti-bot requirement but will full opensource soon
btw if you want to use the same API, try https://cloud.debank.com/, most of API can be found in DeBank Cloud

**Comment by wsdt** [comment]
ok thanks! But there is no open sourced debank API alternative right? @vvvvvv1vvvvvv 
Appreciating your reply

**Comment by qsmxise02d7zx78q** [comment]
There is no excuse for making a closed source cryptocurrency wallet (and then claiming that it's open source). It looks like people behind Rabby are trying to hide something. It is very hard to trust this project after this incident.

**Comment by nikicat** [comment]
Hello, why is it issue closed? There are still no sources and no license for this module.

**Comment by wsdt** [comment]
@nikicat because they prefer to keep it closed source. We are using a different wallet now

**Comment by nikicat** [comment]
@wsdt could you tell me which wallet you use?

BTW, I've dug a bit into Rabby sources and found out that their API could be partially replaced by providing custom chains' RPCs (like Infura and Alchemy), but a significant part of functionality depends on their API. Moreover, in my local build all requests to Rabby API return 429 HTTP error code so the extension doesn't work.

**Comment by wsdt** [comment]
@nikicat we actually forked Enkrypt, this is our wallet now with extended functionality: 
https://scramble-wallet.com
