### ISSUE TITLE
0.7.1 release in not yet in Chrome store

### ISSUE THREAD

**Issue by paulvi** [RabbyHub/Rabby#153]
I have just installed this plugin from
https://chrome.google.com/webstore/detail/rabby/acmacodkjbdgmoleebolmdjonilkdbch/

But in Settings it says version is
`version: 0.6.0 / 2021-07-19T10:37:47.082Z` not the latest 0.7.1 released 2 days ago

**Comment by vvvvvv1vvvvvv** [comment]
Chrome store will audit each release(it will cost about 5 work days for now), so we will publish to Chrome store each 2 weeks

**Comment by vvvvvv1vvvvvv** [comment]
You can install it from https://github.com/RabbyHub/Rabby/releases

**Comment by paulvi** [comment]
There is definitely some value for for Google audits

I will check in 3 days if 0.7.1 is available


If you intentionally skip some releases from publishing, 
then better add not in README about what is your release process is.
BTW, some hints how to build would be good

**Comment by vvvvvv1vvvvvv** [comment]
> I will check in 3 days if 0.7.1 is available

Afraid not, next time we submit to Chrome Store is Aug 2th UTC+8, you can use it from Chrome Store at Aug 7th or later

> If you intentionally skip some releases from publishing, then better add not in README about what is your release process is

Actually GitHub release will be faster than Chrome Store since Rabby is still in high-speed development but Chrome Store audit is slow. But it should be temporarily, after Rabby functionality got stable, we will make these two release synchronous

> BTW, some hints how to build would be good

lol thanks, coming soon
