### ISSUE TITLE
Clear sign broken with 0.93.3

### ISSUE THREAD

**Issue by AdamB2023** [RabbyHub/Rabby#2665]
Rabby browser extension 0.93.3 broken clear sign.
Sending USDT on BEP20 result in blind sign.
It worked correctly with 0.93.1.

**Comment by vvvvvv1vvvvvv** [comment]
Clear Signing caused a lot of bugs. Within two weeks of enabling it, we received hundreds of cases of signature failures caused by Clear Signing, so we had to disable it. We have reported all the problems to the Ledger team and are waiting for them to fix them. If Clear Signing no longer has bugs, we will re-enable it.

**Comment by vvvvvv1vvvvvv** [comment]
![telegram-cloud-photo-size-5-6240050696531590955-x](https://github.com/user-attachments/assets/9ccb1be7-09fd-492f-abe9-a8341737dbd8)
![telegram-cloud-photo-size-5-6240050696531590954-y](https://github.com/user-attachments/assets/d52eb1e8-127e-4ca4-9490-7d2c0ffe3535)
![telegram-cloud-photo-size-5-6211007023869443805-y](https://github.com/user-attachments/assets/19d22287-185e-41a1-8d1d-81d394eeacc1)
![telegram-cloud-photo-size-5-6211007023869443807-y](https://github.com/user-attachments/assets/47f876db-9263-4476-afcd-223a1c1eea16)

If you strongly want to use Clear Signing and don't care about potential problems, you can use the previous version of Rabby (download here https://github.com/RabbyHub/Rabby/releases/tag/v0.93.2)
