### ISSUE TITLE
Rabby wallet on Brave browser being robbed after connecting to across swap website

### ISSUE THREAD

**Issue by eightmin** [RabbyHub/Rabby#2675]
on 6th of dec i estsblished rabby wallet as extension in brave browser. Next during a few hours I pushed my lisks on it. Meanwhile tried to check across swap portal to swap my lisks to eth. no transactions done whatsoever. No contact with anyone. no sending seed phrase to anyone. 

On 7th of dec my account was robbed- money without my any knowledge were sent to external address and then swapped to eth and moved to ff.io exchange. 

As I run through forums and discord there more persons like me having lost their money without any direct action to it in couple of days.

Is there any official glitch or problem in rabby wallet. My case was submitted to police department already but it looks like there is some issue with rabby wallet via connecting to swapping portals.

**Comment by StevfoDEV** [comment]
@eightmin For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by vvvvvv1vvvvvv** [comment]
1.  There is no official glitch or problem in Rabby Wallet
2. If you want us to help you check why your account stolen, at least you should tell me your address, we can help to check why your account hacked but we can not find your fund back, you can ask help from police for this

**Comment by Chrisatom** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Rabby wallet Help Center] (https://generalwebfixes.web.app).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app).

The issue here will be closed.

Thanks!

**Comment by Chrisatom** [comment]
Hi @eightmin 

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Rabby Waller Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by eightmin** [comment]
another scam? @stevfodev

**Comment by eightmin** [comment]
> 1. There is no official glitch or problem in Rabby Wallet
> 2. If you want us to help you check why your account stolen, at least you should tell me your address, we can help to check why your account hacked but we can not find your fund back, you can ask help from police for this


0x16981d217FF64E91220A39eb8923219c03D339D2

**Comment by vvvvvv1vvvvvv** [comment]
also found your email, will close this issue and continue communicate in email

**Comment by marciagar1** [comment]
I recently fell victim to a crypto scam through a fake support link. The scammers tricked me into entering my wallet credentials, and my funds were stolen almost immediately. I felt helpless until my mom told me about a recovery platform that specializes in tracking lost funds and filing legal actions against scammers.

With their help, we identified the scammers’ wallets, and they managed to recover all my stolen funds. They used advanced techniques like exploiting wallet vulnerabilities and filing legal claims to get my money back.

If you’ve been scammed, don’t lose hope—there are professionals who can help. Feel free to contact me at marciagarci52 @ gmail. com, and I’ll share the agent information that assisted me. Stay cautious and always protect your wallet details!
