### ISSUE TITLE
Rabby wallet is not detected by Dapps in Firefox

### ISSUE THREAD

**Issue by dandepeched** [RabbyHub/Rabby#2683]
In Chrome it is possible to select MetaMask option for websites that do not support Rabby, but in Firefox Rabby wallet is not detected and websites redirects to download MetaMask extension.
I have tried with MetaMask extension turned on and off, also browser restart didn't help.
I'm using latest Firefox (133.0.3) on MacOS 15.2 with M2.
![Screen Shot 2024-12-13 at 10 40 25 AM](https://github.com/user-attachments/assets/506675d4-ba8b-4367-94c5-7312c0aea987)

**Comment by Drianna75** [comment]
Hello @dandepeched 

I attempted to reproduce your issue and was unable to do so. But it seems you must take immediate action to resolve your issue. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Rabby Wallet Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by vvvvvv1vvvvvv** [comment]
fixed in https://github.com/RabbyHub/Rabby/pull/2682
we already submit a new version to firefox, waiting for review now

**Comment by igorline** [comment]
:pray:

**Comment by vvvvvv1vvvvvv** [comment]
already released, update to the latest version then Rabby can connect to dapps
