### ISSUE TITLE
Add testnet network

### ISSUE THREAD

**Issue by thanhlmm** [RabbyHub/Rabby#409]
I want to connect some app on testnet chain like ETH Rinkeby but I can not add new network to Rabby

**Comment by vvvvvv1vvvvvv** [comment]
duplicated  with #261

**Comment by BadgerlockT** [comment]
This is not a duplicate of #261.
#261 refers to adding Custom RPCs, which would be done to existing networks. We also need the ability to add other networks that Rabby does not already have preconfigured.
Either this should be an additional feature request, or #261 should be updated to include adding new networks. Thanks!

**Comment by PhilippeR26** [comment]
@thanhlmm is right ; access to testnets is missing, and it's not related to #261.
I would like to access to Goerli and Sepolia, but it's not possible with Rabby.
As Moonbeam has been implemented, it should be not so difficult to implement these testnets.
As I am developping in starknet, I need absolutely the access to Goerli. 
So Metamask will remain my wallet until this issue is merged.
